### ISSUE TITLE
firebase messeging error

### ISSUE THREAD

**Issue by yiminwook** [yiminwook/liveuta#109]
```javascript
Error: An unknown server error was returned. Raw server response: "<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/batch</code> was not found on this server.  <ins>That’s all we know.</ins>
". Status code: 404.
    at async f (.next/server/app/api/push/route.js:1:4143)
    at async (.next/server/chunks/8872.js:19:60764) {
  errorInfo: [Object],
  codePrefix: 'messaging'
}
```

옛날 버전이라서 sdk가 deprecated 된듯.. 최신화 필요

**Comment by yiminwook** [comment]
@utawakuworker 

일단 메시지 스케줄 돌리는거 막아 줄 수 있음?

어차피 안될거 그리고 개선하면서 그냥 내가 돌리려구 

테이블 새로짜서 유저에 토큰 맵핑해서 관리하려고함

**Comment by utawakuworker** [comment]
> @utawakuworker
> 
> 일단 메시지 스케줄 돌리는거 막아 줄 수 있음?
> 
> 어차피 안될거 그리고 개선하면서 그냥 내가 돌리려구
> 
> 테이블 새로짜서 유저에 토큰 맵핑해서 관리하려고함

ㅇㅇㅇ 알림 안간지 좀 되긴 했는데 그동안 말은 안했었어 ㅋㅋ;
